Add api auth
aaaandrzej/CV_Editor pull request #16
Opened 2020-10-30 18:07 UTC by pgs-aszulc

Główne rzeczy chyba zrobione, do dopisania testy i readme, przysiądę do tego w następnej kolejności

2020-11-04 06:51 UTC, pgs-pdalka requested changes

2020-11-04 06:51 UTC, pgs-pdalka commented on alembic/versions/4fe95ab59d48_.py
> +    sa.Column('admin', sa.Boolean(), nullable=True),
Ustaw  `nullable=False` i dodaj wartość domyślną False

2020-11-04 06:51 UTC, pgs-pdalka commented on app/functions.py
> +def error_response(msg: str, status: int, ex: Exception = None) -> Tuple[dict, int]:
`ex: Optional[Exception] = None`

2020-11-04 06:51 UTC, pgs-pdalka commented on app/main.py
> +        if current_user.id != int(user_id):
Możesz połączyć te dwa ify w jeden

2020-11-04 06:51 UTC, pgs-pdalka commented on app/main.py
> +    if cv_being_updated.password != '':
Trochę zmian w logice endpointów - PUT nie może zmieniać hasła, do tego jest osobny endpoint

2020-11-04 06:51 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_id_password(id: int) -> Tuple[dict, int]:
I tu zmiana logiki: ten endpoint powinien wymagać autoryzacji, payload z hasłem starym (weryfikowanym) i nowym bez zmian. Hasło może zmienić użytkownik tylko sam sobie.

W aplikacji brakuje jeszcze mechanizmu "przypomnij hasło i zmień", ale to sobie darujemy.

2020-11-04 06:51 UTC, pgs-pdalka commented on app/models.py
> +    admin = Column(Boolean)
To pole powinno być takie, jak skomentowałem w migracji

2020-11-04 06:51 UTC, pgs-pdalka commented on tests/app/unit/test_identify.py
> +    assert actual == ({'admin': True, 'experience': [], 'firstname': 'te', 'id': None, 'lastname': 'st', 'skills': [], 'username': 'test'}, 200)
Dobrze jest, żeby testowych wartości nie powtarzać w mocku i potem przy sprawdzaniu, tylko żeby było one w teście zdefiniowane tylko w jednym miejscu, w potem ponownie użyte

2020-11-04 15:56 UTC, pgs-aszulc commented on app/main.py
> +        if current_user.id != int(user_id):
na pewno, ale próbuję kolejny raz i nie mogę na to wpaść.

chcę rzucić 'not authorized' w przypadku jeśli jeden z warunków jest spełniony, a drugi nie. próbowałem konstrukcje typu `    if not current_user.admin or current_user.id != int(user_id):`  ale to nie działa dla nie-admina, którego id się zgadza. wchodzi mi do środka ifa dlatego, że zgadza mu się warunek `if not admin`

2020-11-04 16:27 UTC, pgs-aszulc commented on app/main.py
> +def api_cv_id_password(id: int) -> Tuple[dict, int]:
nie wiem jak mi to uciekło, absolutnie racja, uwierzytelnianie dodane

2020-11-04 16:37 UTC, pgs-aszulc commented on alembic/versions/4fe95ab59d48_.py
> +    sa.Column('admin', sa.Boolean(), nullable=True),
zmieniłem w models.py na `admin = Column(Boolean, nullable=False, default=False)` i wygenerowałem nową migrację, alembic wyłapał nullable ale nie wyłapał default, i teraz w migracji jest `sa.Column('admin', sa.Boolean(), nullable=False),`

powinienem dopisać z palca default w migracji, czy coś robię źle z models.py?

2020-11-04 16:38 UTC, pgs-aszulc commented on app/models.py
> +    admin = Column(Boolean)
https://github.com/aaaandrzej/CV_Editor/pull/16#discussion_r517477785

2020-11-04 16:42 UTC, pgs-aszulc commented
przy okazji jedna wątpliwość dotycząca logiki. skoro tylko admin może dodawać nowe cv/ userów, a zaczynam z pustą bazą (gdzie nie ma nawet admina) to jak mam stworzyć pierwszego usera/ admina? mogę dodać admina do migracji bazy? czy nie przejmować się tutaj tym i dodawać go bezpośrednio w bazie?

2020-11-04 18:55 UTC, pgs-aszulc commented on alembic/versions/1c3960828216_start.py
> +    sa.Column('admin', sa.Boolean(), nullable=False),
to jest zmiana wspominana w https://github.com/aaaandrzej/CV_Editor/pull/16#discussion_r517477785

2020-11-04 18:56 UTC, pgs-aszulc commented on app/functions.py
> +        return False
tak sobie wymyśliłem sprawdzanie czy użytkownik jest unikalny, ale mam watpliwość czy nie lepiej tego zrobić try except i łapać IntegrityError

2020-11-04 18:57 UTC, pgs-aszulc commented on app/main.py
> +    except (DataError, IntegrityError) as ex:
tu jest rozwiązanie z try-except do sprawdzania unikalności użytkownika

2020-11-04 19:03 UTC, pgs-aszulc commented on app/main.py
> +            return error_response('bad input data', 400, None)
tutaj unikalność username sprawdzam ifami przy użyciu dodanej funkcji - brzydkie to jak noc, ale mam problem z zaprojektowaniem tej logiki w sensowniejszy sposób. chodzi mi po głowie jakaś dodatkowa zmienna, ale nie wiem czy to rozsądny kierunek.

2020-11-04 19:03 UTC, pgs-aszulc commented on app/main.py
> +            return error_response('not authorized', 401, None)
dodany @token_required ale i skopiowany potworek z ifami, więc pewnie też do refactoru

2020-11-04 19:03 UTC, pgs-aszulc commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
duże uproszczenie, ale jeśli mam testować każdy możliwy scenariusz to to będzie sporo roboty, i chyba wolałbym ten czas na coś innego poświęcić ;)

2020-11-05 14:57 UTC, pgs-aszulc commented on app/main.py
> +            return error_response('bad input data', 400, None)
tutaj w drugim ifie musiałem wywalić not, wyszło przypadkiem w dzisiejszych testach. ale nadal zostaje to do uproszczenia...

2020-11-05 14:58 UTC, pgs-aszulc commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
musiałem tu jeszcze zmienić '' na 'xxx' bo inaczej się split z auth.py wywalał w testach behave

2020-11-06 06:40 UTC, pgs-pdalka commented on alembic/versions/4fe95ab59d48_.py
> +    sa.Column('admin', sa.Boolean(), nullable=True),
Możliwe, że alembic nie wyłapał, bo czasem tak ma. Ale możliwe też, że poinieneś użyc `server_default` zamiast `default` - poczytaj, jakie są różnice między nimi

2020-11-06 06:41 UTC, pgs-pdalka commented on app/main.py
> +        if current_user.id != int(user_id):
Poniższe nie działa?
`if not current_user.admin and current_user.id != int(user_id)`

2020-11-06 06:54 UTC, pgs-pdalka requested changes

2020-11-06 06:54 UTC, pgs-pdalka commented on README.md
> +    "password": "dupa",
No ale tego to chyba nie chcesz zostawić w repo ;)

2020-11-06 06:54 UTC, pgs-pdalka commented on README.md
> +    "old_password": "dupa"
Tego również :) Plus w wielu innych miejscach

2020-11-06 06:54 UTC, pgs-pdalka commented on app/functions.py
> +        return False
Niech zostanie. Drugim wariantem, który również jest OK, jest sprawdzenie, czy SQLAlchemy nie rzuca wyjątku `IntegrityError` w momencie zrobienia `INSERT/UPDATE`. Plusem tego drugiego rozwiązania jest to, że mamy jedno zapytanie do bazy mniej.

2020-11-06 06:54 UTC, pgs-pdalka commented on app/main.py
> +    except (DataError, IntegrityError) as ex:
O, już masz `InegrityError`. Więc funkcja `check_if_username_unique` nie powinna być potrzebna

2020-11-06 06:54 UTC, pgs-pdalka commented on app/main.py
> +        if check_if_username_unique(session, json_data['username']):
Jeśli jednak nie wywalimy funkcji `check_if_username_unique` to tutaj można przecież napisać:
`if cv_being_updated.username != json_data['username'] and check_if_username_unique(session, json_data['username']):`

2020-11-06 06:54 UTC, pgs-pdalka commented on app/main.py
> +        if current_user.id != int(user_id):
`if not current_user.admin and current_user.id != int(user_id):`

2020-11-06 06:58 UTC, pgs-pdalka commented
> przy okazji jedna wątpliwość dotycząca logiki. skoro tylko admin może dodawać nowe cv/ userów, a zaczynam z pustą bazą (gdzie nie ma nawet admina) to jak mam stworzyć pierwszego usera/ admina? mogę dodać admina do migracji bazy? czy nie przejmować się tutaj tym i dodawać go bezpośrednio w bazie?
> 
> EDIT: obszedłem to w końcu skryptem init_db.py - dodane również do Makefile i opisane w README.md

Dodanie admina w pierwszej migracji byłoby o tyle lepsze, że miałbyś to zrobione z automatu przy wchodzenia na każde nowe środowisko (stage, prod itd). W Twoim rozwiązaniu admina trzeba by zawsze dodawać ręcznie

2020-11-06 07:00 UTC, pgs-pdalka commented on app/main.py
> +            return error_response('bad input data', 400, None)
A dlaczego w tym przypadku też nie możesz po prostu złapać `IntegrityError`?

2020-11-06 07:13 UTC, pgs-pdalka commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
Ten fragment jest faktycznie brzydki. Jeśli token nie jest ustawiony, to nie pownieneś go w ogóle wysyłać w requeście, a nie wysyłać jakieś `xxxx`. A najprościej to zrobić wstawiając to `context` nie `token`, ale już gotowe nagłówki, czyli:
`context.header = {'Authorization': f'Bearer {token}'})`
lub
`context.headers = None` (to możesz dodać do `before_scenario`, aby zawsze było zdefuciowane.
I potem przy wysyłaniu requestu piszesz po prostu `headers=context.headers`

Ale gorsze jest to, co napisałeś, że "bo inaczej się split z auth.py wywalał" - no tak być nie może :) Masz w module `auth` `token = token.split(' ')[1]`, więc to się wywali z `IndexError` w przypadku, gdy wartość nagłówka nie będzie miała spacji. Dodaj więc łapanie `IndexError` dwa wiersze niżej i będzie git. Tylko, że taki case powinien być pokryty w unit testach...

2020-11-06 10:51 UTC, pgs-aszulc commented on alembic/versions/4fe95ab59d48_.py
> +    sa.Column('admin', sa.Boolean(), nullable=True),
Poczytałem, poeksperymentowałem, i mam takie wnioski:
- alembic jest znany z tego, że nie łapie default, ludzie to obchodzą np. podawaniem obu default=False i server_default='f'
- server_default nie przyjmuje wartości bool, próbowałem go obejść sqlalchemy.sql.expression.false() ale to też nic sensownego nie dało
- w moich zastosowaniach wg mnie to jest dość drugorzędne czego użyję, albo tego do końca nie rozumiem
- po kilku eksperymentach koniec końców dopisałem z palca w migracji default=False, sprawdziłem, i działa - zostawiłbym to już tak (czyli `    sa.Column('admin', sa.Boolean(), nullable=False, default=False),`)

2020-11-06 11:03 UTC, pgs-aszulc commented on app/main.py
> +        if current_user.id != int(user_id):
no działa, nie wiem czemu próbowałem do upadłego z OR - dzięki

2020-11-06 11:05 UTC, pgs-aszulc commented on app/functions.py
> +        return False
Integrity Error robiłem gdzie indziej, i się właśnie wahałem co lepsze - to wywalam tą funkcję i wracam do try/except

2020-11-06 11:12 UTC, pgs-aszulc commented on app/main.py
> +    except (DataError, IntegrityError) as ex:
już jej nie ma :)

2020-11-06 13:01 UTC, pgs-aszulc commented on app/main.py
> +            return error_response('bad input data', 400, None)
nie wiedziałem które rozwiązanie jest lepsze, czy weryfikować unikalność username na bardzo wczesnym etapie (i tym samym nie brnąć w dalsze, zbędne operacje) czy może pozwolić dojść funkcji aż do wywołania session.commit() i dopiero wtedy łapać wyjątek. w moim przypadku jest jeszcze funkcja aktualizująca skillsy i musiałem ją dorzucić do 'try', mam nadzieję, że to jest ok (linia 170 w main.py)

2020-11-06 14:42 UTC, pgs-aszulc commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
xxx i to z auth.py wybacz, najpierw nie chciałem tego w ogóle testować, a później stwierdziłem że zrobię coś na szybko, żeby zadziałało i "coś sprawdziło" :)

A co do before_scenario - próbowałem z before_all, teraz też sprawdziłem before_scenario (oba zdefiniowane w environment.py) i mi to nie działa. Wcześniej miałem już problem z przekazywaniem context.session, też nie działało. Czy ja to gdzieś muszę dodatkowo doimportować, albo wywołać?

Aktualnie w przypadku braku poniższego obejścia z try/except mam `AttributeError: 'Context' object has no attribute 'header'` co ewidentnie oznacza, że funkcje before nie robią tego co powinny.

Póki co obchodzę to tak:
`    try:
        context.header
    except AttributeError:
        context.header = None
`
ale jestem otwarty na dyskusje.

Plus jest taki, że test jest teraz trochę mniej brzydki. Zmieniłem też odpowiedź endpointu w pliku feature, z token invalid na token missing.

W auth dodałem IndexError do excepta z invalid token, a unit testów auth nie pisałem w ogóle. Jeśli są niezbędne, to dopiszę...

2020-11-06 14:46 UTC, pgs-aszulc commented on README.md
> +    "password": "dupa",
Ale że ujawnianie sekretu, przekleństwa, czy polskie wyrazy nie są OK? :)

Zostawiłem to z premedytacją, jako "jakieś przykładowe kredki" - mogę to zamienić na sample_user i sample_password jeśli to będzie bardziej profesjonalne :)

2020-11-06 14:49 UTC, pgs-aszulc commented on README.md
> +    "old_password": "dupa"
już jest password i new_password :) a secret zmieniłem na secretkey - ok?

2020-11-06 14:50 UTC, pgs-aszulc commented on app/main.py
> +        if check_if_username_unique(session, json_data['username']):
wywaliłem, zgadzam się, że IntegrityError jest sensowniejsze, chociaż za używaniem tej mojej funkcji też miałem argumenty - pisałem o tym gdzie indziej

2020-11-06 15:05 UTC, pgs-aszulc commented on app/main.py
> +        if current_user.id != int(user_id):
yes

2020-11-06 15:56 UTC, pgs-aszulc commented
Chyba wszystkie uwagi poza dodawaniem pierwszego admina przez migrację ogarnięte, muszę sobie przypomnieć sql żeby zrobić sparametryzowane query, bo trochę mi ta wiedza zwietrzała. Ogarnę i dopchnę zmiany jak będzie gotowe.

2020-11-09 07:00 UTC, pgs-pdalka commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
Niech zostanie łapanie `AttributeError`. Natomiast nie powinno być żadnych problemów z ustawieniem zmiennych contekstu w `before_scenario` - u mnie działa :)

2020-11-09 07:01 UTC, pgs-pdalka commented on README.md
> +    "password": "dupa",
Używanie brzydkich wyrazów zdecydowanie nie jest profesjonalne :)

2020-11-09 07:09 UTC, pgs-pdalka commented on alembic/versions/2_create_admin.py
> +    DELETE FROM user WHERE username = 'admin';
Zrób to najprościej:
`f'''query = 'DELETE FROM user WHERE username = '{app_admin_user.username}';'''`

2020-11-09 07:11 UTC, pgs-pdalka approved these changes

2020-11-09 07:14 UTC, pgs-pdalka commented on tests/app/component/features/steps/api_cv_post.py
> +        context.token = ''
Po chwilowym namyśle stwierdzam, że takie wiszące `context.header` jest średnie, więc wstaw:
`
if not hasattr(context, 'header'):
    context.header = None
`

2020-11-09 11:49 UTC, pgs-aszulc commented on README.md
> +    "password": "dupa",
oj tam brzydkich, teraz granica używania wulgaryzmów w życiu publicznym się przesunęła... (dobra, dawno zmienione :) )

2020-11-09 11:50 UTC, merged