Db model upgrade
aaaandrzej/CV_Editor pull request #7
Opened 2020-08-12 17:28 UTC by aaaandrzej

Hej, dopracowałem model bazy i pierwszy endpoint (api_cvi_get) wydaje się wreszcie zwracać poprawne dane, w formacie json, z zagnieżdżonymi w środku wartościami z innych tabel. Jeśli możesz to zerknij w to proszę czy to jest dobry kierunek, bo strasznie się z tym naszarpałem :)

2020-08-13 06:19 UTC, pgs-pdalka commented on app/models.py
> +    def object_as_dict_string(self):
Nie widzę żadnej korzyści (a nawet widzę wady) w zwracaniu tutaj stringa, zamiast dicta

2020-08-13 06:21 UTC, pgs-pdalka commented on app/main.py
>  @app.route('/api/cv/', methods=['GET'])  # TODO czy tak się robi? czy w <id> też dorobić / po adresie?
Ten endpoint zwraca CV wszystkich użytkowników, więc jego url jest właściwy :)

2020-08-13 06:23 UTC, pgs-pdalka commented on app/main.py
> +    all_db_records = [user.object_as_dict_string() for user in session.query(User)]
Ponieważ `object_as_dict_string` zwraca string, to w efekcie uzyskujesz tutaj listę stringów. A powinna być po prostu lista dictów, gdzie każdy dict to CV jednego usera

2020-08-13 06:23 UTC, pgs-pdalka commented on app/main.py
>      return json.dumps(all_db_records)
`json.dump` jest zbyteczne - Flask sam z siebie wykona tą operację; wystarczy `return all_db_records`

2020-08-13 08:49 UTC, aaaandrzej commented on app/main.py
>  @app.route('/api/cv/', methods=['GET'])  # TODO czy tak się robi? czy w <id> też dorobić / po adresie?
ok :) generalnie to pytanie dotyczyło obu linii:

@app.route('/api/cv', methods=['GET'])
@app.route('/api/cv/', methods=['GET'])

zastanawiałem się, czy powinienem mieć i jeden i drugi endpoint (w wersji www /cv/ wywalało błąd, musiałem użyć /cv lub /cv/34 i stąd to obejście

2020-08-13 08:54 UTC, aaaandrzej commented on app/models.py
> +    def object_as_dict_string(self):
Oj próbowałem, wielokrotnie, i dostawałem: TypeError: Object of type SkillUser is not JSON serializable

Nawet po wywaleniu json.dumps z returna w funkcji endpointu (inna uwaga stąd) pojawia się błąd:
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.

Także to co mam to jedyne co mi zadziałało i dlatego tak zrobiłem.

2020-08-13 08:57 UTC, aaaandrzej commented on app/main.py
> +    all_db_records = [user.object_as_dict_string() for user in session.query(User)]
No właśnie return w apce flaskowej nie chce przyjąć listy i po usunięciu json.dumps() z linii poniżej wypluwa:

TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.

Dlatego ten json.dumps w tym endpoincie mi się sprawdził, a żeby on działał, to w modelu muszę mieć tą funkcję object_as_dict_string() z str()

2020-08-13 08:58 UTC, aaaandrzej commented on app/main.py
>      return json.dumps(all_db_records)
tak powyżej, bez niego nie działa :)

TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.

2020-08-18 06:22 UTC, pgs-pdalka commented on app/main.py
> +        response = json.dumps(one_db_record.object_as_dict_string())
Użyj `object_as_dict`, bo w tej postaci zwróciłeś stringa skonwertowanego do stringa komendą `json.dumps`

2020-08-18 06:28 UTC, pgs-pdalka commented on app/main.py
> +    if "skills" in json_data and len(json_data["skills"]) > 0:  # if skills:
Zamiast tego całego ifa wystarczy `if json_data.get('skills'):` - będzie prawdą tylko wtedy, gdy klucz `skill` istnieje i zawiera niepustą listę

A jeszcze lepiej użyj walrus operator (nowość w Python 3.8):
`if (skills := json_data.get('skills')):` - i w zmiennej `skills` masz już tą listę, więc niżej możesz napisać po prostu `for skill in skills:`

A jeszcze lepiej zamiast ifa i for od razu daj for:
`for skill in json_data.get('skills', []):`

2020-08-18 06:37 UTC, pgs-pdalka commented on app/main.py
> +    except UnmappedInstanceError as ex:  # TODO zamienić Exceptions na poprawny błąd - Class 'builtins.NoneType' is not mapped
Zamiast łapać wyjątek z SQLAlchemy, lepiej sprawdź, czy `cv_to_be_deleted` nie jest `None` i tylko wtedy kasuj rekord.

2020-08-18 06:43 UTC, pgs-pdalka commented on app/main.py
> +    return json.dumps(all_db_records)  # TODO halo Piotr, czy da się bez json.dumps - zgodnie z uwaga z PR?
Już odrobiłem pracę domową. Nie możesz zwrócić bezpośrednio listy czy też dicta z funkcji endpointu w czystym Flasku. Musisz najpierw zserializować go do JSONa, tylko że poprawnym rozwiązaniem jest użycie Flaskowego `jsonify` zamiast `json.dumps`:
```
from flask import jsonify
return jsonify(some_dict)
```

2020-08-18 09:21 UTC, aaaandrzej commented on app/main.py
> +    if "skills" in json_data and len(json_data["skills"]) > 0:  # if skills:
to ostatnie jest ekstra faktycznie, już zmieniam, dzięki :) na moją obronę, to całe spagetti najpierw ma zadziałać, a później będzie refactor, więc póki co jakoś specjalnie się nie przejmowałem tymi piramidkami ;)

2020-08-18 17:12 UTC, aaaandrzej commented on app/main.py
> +    except UnmappedInstanceError as ex:  # TODO zamienić Exceptions na poprawny błąd - Class 'builtins.NoneType' is not mapped
done :)

2020-08-18 17:22 UTC, aaaandrzej commented on app/main.py
> +    return json.dumps(all_db_records)  # TODO halo Piotr, czy da się bez json.dumps - zgodnie z uwaga z PR?
dzięki za odrobienie pracy domowej za mnie, fajne to jsonify :)

dołożyłem jeszcze config flaska który zapobiega sortowaniu rezultatu, bo początkowo miałem najpierw experience a dopiero później firstname. 

app = Flask(__name__)
app.config['JSON_SORT_KEYS'] = False

2020-08-18 17:49 UTC, aaaandrzej commented
hej, zakładam, że ten branch jest gotowy do zmergowania z masterem, celem było odtworzenie dawnych funkcjonalności ale w oparciu o nowy model bazy - i generalnie to (moim zdaniem) działa. 

jest kilka pytań w kodzie, jeśli masz czas i chęć to zerknij, a jak nie to pogadamy przy okazji - nie ma tam nic co by mnie blokowało, więc na spokojnie.

jeśli chodzi o kolejne kroki to widzę to tak o, ale daj proszę znać,  jeśli to złe podejście:
kolejny endpoint pod statystyki zbiorcze, migracja na postgresql, autoryzacja/ autentykacja, testy, deployment do aws

2020-08-19 05:19 UTC, pgs-pdalka requested changes

2020-08-19 05:19 UTC, pgs-pdalka commented on app/models.py
> +            # TODO dlaczego pycharm podswietla na zolto self.skills?
Tu i niżej: Python jest językiem dynamicznym i choć PyCharm robi co może, to w przypadkach skomplikowanych (a SqlAlchemy robi magię) nie jest w stanie prawidłowo domyślić się typu (w tym przypadku `self.skills`). Można próbować to obejść, ale zwykle lepiej po prostu zignorować.

2020-08-19 05:19 UTC, pgs-pdalka commented on app/main.py
> +    # TODO czy powinienem usuwac z bazy skille, ktorych nie bylo w jsonie??
Z tabeli `SkillName`  - nie. Z tabeli `SkillUser` - jak najbardziej. Widzę, że ten endpoint będzie jeszcze wymagał refaktoringu :)

2020-08-19 05:32 UTC, pgs-pdalka requested changes

2020-08-19 05:32 UTC, pgs-pdalka commented on app/main.py
> +    return "For API please use /api/cv or /api/cv/<id>"  # TODO jak to zmusić do wyświetlania <id> w safari? po uruchomieniu tego w przeglądarce mam: "For API please use /api/cv or /api/cv/"
Przypuszczam, że należałoby ustawić nagłówek `"Content-Type: text/plain"`, bo domyślnie widać jest `text/html` i `<id>`  przeglądarka interpretuje jako tag htmlowy. Możesz to zrobić np:

```
from flask import Response

return Response('text', mimetype='text/plain')
```

2020-08-19 05:32 UTC, pgs-pdalka commented on app/main.py
> +        new_cv.skills.append(skill_object)  # TODO dlaczego pycharm podswietla append na zolto..?
Ten sam powód, co poprzednio

2020-08-19 05:32 UTC, pgs-pdalka commented on app/main.py
>          return "", 202
Zgodnie z konwencją, tu powinien być status 204

2020-08-19 05:32 UTC, pgs-pdalka commented on app/main.py
>      return "", 202
Zgodnie z konwencją, tu powinien być status 200

2020-08-19 05:32 UTC, pgs-pdalka commented on app/main.py
> +    if "skills" in json_data.keys():  # TODO kod jest zduplikowany z funkcją POST, czy powinienem to przerobić na funkcje add_skills() i add_experience() i wynieść poza endpointy?
Generalnie tak - wszystkie fragmenty kodu używane wielokrotnie powinny być wydzielone do osobnej funkcji

2020-08-19 05:39 UTC, pgs-pdalka commented
> jeśli chodzi o kolejne kroki to widzę to tak o, ale daj proszę znać, jeśli to złe podejście:
> kolejny endpoint pod statystyki zbiorcze, migracja na postgresql, autoryzacja/ autentykacja, testy, deployment do aws

Jeszcze trochę popracujemy nad tymi endpointami, bo o ile działają, to nie są optymalne. W pierwszej kolejności proponuję Ci przepięcie się na postgresql w dockerze - odpoczniesz chwilę od tych endpointów ;) A potem tuning istniejących endpointów + ten do statystyk zbiorczych.

2020-08-19 08:19 UTC, aaaandrzej commented on app/models.py
> +            # TODO dlaczego pycharm podswietla na zolto self.skills?
chętnie zignoruję, dzięki! :)

2020-08-19 08:23 UTC, aaaandrzej commented on app/main.py
> +    # TODO czy powinienem usuwac z bazy skille, ktorych nie bylo w jsonie??
ok, to wrócimy do tematu - mam w głowie kilka scenariuszy jak by to mogło wyglądać, chyba nawet sporo prawie gotowego kodu do wykorzystania

2020-08-19 08:29 UTC, aaaandrzej commented on app/main.py
> +    return "For API please use /api/cv or /api/cv/<id>"  # TODO jak to zmusić do wyświetlania <id> w safari? po uruchomieniu tego w przeglądarce mam: "For API please use /api/cv or /api/cv/"
działa, dzięki. a na przyszłość trochę więcej pogoogluję zanim zadam pytanie - albo będę oznaczał jakoś pytania które powinienem zadawać sam do siebie ;)

2020-08-19 08:30 UTC, aaaandrzej commented on app/main.py
>          return "", 202
done

2020-08-19 08:31 UTC, aaaandrzej commented on app/main.py
>      return "", 202
done

2020-08-19 08:32 UTC, aaaandrzej commented on app/main.py
> +    if "skills" in json_data.keys():  # TODO kod jest zduplikowany z funkcją POST, czy powinienem to przerobić na funkcje add_skills() i add_experience() i wynieść poza endpointy?
ok, to na przyszłość chętnie, ale skoro tutaj endpoint PUT ma iść do zmian (a POST być może się uchowa) to bym to na razie tak zostawił, żeby nie zmieniać czegoś co i tak wyleci

2020-08-19 08:33 UTC, aaaandrzej commented
ok :)

2020-08-19 08:41 UTC, merged