Endpoints refactor
aaaandrzej/CV_Editor pull request #9
Opened 2020-08-24 21:40 UTC by aaaandrzej

hej, jak masz chwilę to możesz zerknąć w kod, zwłaszcza:
- refactor endpointów POST i PUT - usprawnienie zapytań zgodnie z rozmową i wydzielenie funkcji do functions.py
- type annotations
- endpoint STATS, a raczej jego początek

nie udało mi się zmusić sqlalchemy do wyciągania użytkowników którzy mają skill_name wraz z odpowiednim skill_level, chociaż próbowałem na milion sposobów. obszedłem to operacjami na liście wyciągniętych użytkowników, ale mam obawy, że nie do końca o to ci chodziło. będę wdzięczny za podpowiedź :)

ściągnąłem też plugin envfile i próbowałem ogarnąć te zmienne środowiskowe, ale jedyne co mi z tego póki co wyszło, to błędy. jeśli masz pod ręką coś co mnie naprowadzi na dobry kierunek to będę wdzięczny, a jak nie to może ogarniemy to razem w środę? zostawiłem część kodu zakomentowane, żeby od tego wyjść jeśli coś z tego ma sens.

2020-08-25 07:35 UTC, pgs-pdalka requested changes

2020-08-25 07:35 UTC, pgs-pdalka commented on app/functions.py
> +    for json_exp in json_data.get('experience', []):
```
cv.exerience = [
     Experience(
        company=json_exp['company'],
        project=json_exp['project'],
        duration=json_exp['duration']
    ) for json_exp in json_data.get('experience', [])
]
```

2020-08-25 07:35 UTC, pgs-pdalka commented on app/functions.py
> +def replace_experience_with_json(cv: object, json_data: dict) -> None:
`cv: User`

2020-08-25 07:35 UTC, pgs-pdalka commented on app/functions.py
> +    return
`return` jest niepotrzebny

2020-08-25 07:35 UTC, pgs-pdalka commented on app/functions.py
> +    return
`return` jest niepotrzebny

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_get() -> jsonify:
`jsonify` to nazwa funkcji, więc nie może być podana jako typ zwracanego obiektu :) Jak spojrzysz w źródła Flaska (albo przeczytasz dokumentację funkcji) to zobaczysz, że funkcja `jsonify` zwraca obiekt `Response`. Czyli `def api_cv_get() -> Response:`

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_post() -> 201:
Ta funkcja nie zwraca `201`, tylko dwuelementową krotkę (tuple), której pierwszy element jest stringiem, a drugi intem. Czyli: `def api_cv_post() -> Tuple[str, int]`
`Tuple` zaimportujesz z modułu `typing`

Polecam lekturę:
https://realpython.com/python-type-checking/

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_id_get(id: int = None) -> jsonify:
Tutaj sprawa się komplikuje jeśli chodzi o zwracany typ (raz jest `Response`, a raz `Tuple[str, int]`). Dla prostoty proponuję zmienić obsługę wyjątku na `return make_reponse('', 404)` i ustawić zwracany typ na `Resonse`

Ponownie zwracam uwagę, by używać apostrofów, a nie cudzysłowi, czyli `''`, a nie `""`

Natomiast argument do funkcji `id`, oznaczyłeś jako typu `int`, który ma wartość domyslną `None`. I tu jest sprzeczoność, bo wartość `None` nie jest przecież typu `int`. Powinno być po prostu `id: int`, bez wartości domyślnej - zawsze coś dostaniesz jako `id`, bo coś musi być podane w adresie, aby dopasowanie ścieżki `/api/cv/<id>` do tej funkcji zadziałało

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_id_put(id: int = None) -> 200:
Poradzisz już sobie z poprawą adnotacji typów :)

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +    for key, value in json_data.items():  # TODO jeśli nie przekażę np firstname to nie zostanie wyczyszczone - to błąd?
Tak, to błąd. Jak mówiliśmy, PUT zastępuje cały istniejący obiekt tym, co dostał w payloadzie.

2020-08-25 07:35 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_id_delete(id: int = None) -> 204:
Adnotacja typów jak wyżej

2020-08-25 07:35 UTC, pgs-pdalka commented on app/session.py
> +# engine = create_engine(f'postgresql://{DB_USER}:{DB_PASSWORD}@localhost:5432/my_db')
To wydaje się ok, dodaj jeszcze nazwę bazy odczytywaną ze zmiennej `DB_NAME`

2020-08-25 07:35 UTC, pgs-pdalka commented on docker-compose.yml
> +#     - POSTGRES_USER = "${DB_USER}"
Zmienne środowiskowe w `docker-compose.yml` podajemy po prostu `POSTGRES_USER = ${DB_USER}`

2020-08-25 07:35 UTC, pgs-pdalka commented on environment.env
> +import os
A ten plik to nie jest fragment kodu Pythona, ale zwyczajne przypsanie, czyli:
```
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=mydb
```

Co więcej, ten plik to jest konfiguracja lokalna Twojego środowiska, czyli jako taki nie jest commitowany do gita.

2020-08-25 07:37 UTC, pgs-pdalka requested changes

2020-08-25 07:37 UTC, pgs-pdalka commented on app/main.py
> +    users_with_skill_name = session.query(User).join(SkillUser).join(SkillName).filter(
Powinno być wszystko wydobywane jednym zapytaniem. Jutro możemy nad tym popracować

2020-08-25 09:16 UTC, aaaandrzej commented on app/main.py
> +def api_cv_post() -> 201:
fakt, nie czuję tego jeszcze do końca, ale chętnie będę używał. długie to, ale narobię dużo kawy i będę dziś czytać :)

2020-08-25 10:45 UTC, aaaandrzej commented on app/main.py
> +    for key, value in json_data.items():  # TODO jeśli nie przekażę np firstname to nie zostanie wyczyszczone - to błąd?
tak mi się wydawało, ale pamiętałem rozmowę gdzie stwierdziliśmy, że to jest OK, i wolałem się upewnić :) 
to przy okazji jeszcze, które rozwiązanie jest bardziej pythonowe? bo chodzą mi po głowie 2:

```
    if 'username' in json_data:
        cv_being_updated.username = json_data['username']
    else:
        cv_being_updated.username = ""
```

czy 

`    cv_being_updated.username = json_data['username'] if 'username' in json_data else ""`

jeśli się da to jeszcze lepiej, to też chętnie przyjmę :)

2020-08-25 10:51 UTC, aaaandrzej commented on docker-compose.yml
> +#     - POSTGRES_USER = "${DB_USER}"
próbowałem tak i tak, ale docker-compose.yml nie pobiera mi zmiennych z pliku env:

> WARNING: The DB_USER variable is not set. Defaulting to a blank string.

nie umiem tego też dodać w konfiguracji. analogiczny problem miałem z resztą w innych miejscach, chyba najłatwiej będzie jak usiądziemy do tego razem

2020-08-25 10:52 UTC, aaaandrzej commented on environment.env
> +import os
tak podejrzewałem, ale chciałem żebyś póki co miał wgląd we wszystko co dotyczy zmiennych środowiskowych :)

2020-08-25 10:53 UTC, aaaandrzej commented on app/main.py
> +    users_with_skill_name = session.query(User).join(SkillUser).join(SkillName).filter(
bardzo chętnie

2020-08-25 12:22 UTC, aaaandrzej commented on app/functions.py
> +def replace_skills_with_json(session: Session, cv: object, json_data: dict) -> None:
przypomniało mi się jeszcze jedno - to dodanie `session` jako parametr funkcji było trochę odkryciem dla mnie, i rozwiązało problemy z sesjami które miałem wcześniej kiedy próbowałem wyodrębnić część fukcjonalności do osobnej funkcji. sam na to wpadłem więc postanowiłem się pochwalić ;)

2020-08-27 06:46 UTC, pgs-pdalka requested changes

2020-08-27 06:46 UTC, pgs-pdalka commented on app/main.py
> +# TODO Piotr, to wyżej czy cv_being_updated.username = json_data['username'] if 'username' in json_data else "" ?
Ten one-liner jest wg mnie bardziej elegancki. Ale to już mocno kwestia upodobań, to co masz też jest ok

aaaaale, to poniżej jest jeszcze lepsze :)
`cv_being_updated.username = json_data.get('username', '')`

2020-08-27 06:46 UTC, pgs-pdalka commented on app/main.py
> +    if 'password' in json_data:
Jak powyżej

2020-08-27 08:30 UTC, aaaandrzej commented on app/main.py
> +# TODO Piotr, to wyżej czy cv_being_updated.username = json_data['username'] if 'username' in json_data else "" ?
wyborne, kradnę :)

2020-08-28 17:28 UTC, aaaandrzej commented
Hej, wpushowałem co miałem, ale to ciągle nie działa dla wyciągania użytkowników po filtrze zawierającym listę/ słownik różnych umiejętności na określonym poziomie.

Próbowałem z hybrid_property, column_property, różnymi wariantami formatowania i za nic nie jestem w stanie porównać tego co jest w User.skills (niezależnie jak bym to tam przechowywał) do wartości przychodzącej w zapytaniu (zamockowanej póki co). Próbowałem nawet z czystym SQL ale tu też poległem, i domyślam się, że muszę to inaczej skonstruować, bo trochę używam Pythona w SQL, co powoduje problem.

Przekopałem cały internet łącznie z dokumentacją SQLAlchemy, ale rezultaty marne.

Wrzucam na chwilę plik __temp.py gdzie są różne zapytania, może któreś będzie do wykorzystania. models.py też ma kilka zakomentowanych prób usprawnienia modelu, żeby umożliwić wykonanie zapytania.

Będę wdzieczny za jakąś podpowiedź :)

Udało się za to, i to bardzo łatwo, policzyć ilość rekordów spełniających te podstawowe kryteria - wrzuciłem to jako endpoint stats/count.

2020-08-31 08:31 UTC, pgs-pdalka commented on alembic/env.py
> +def get_url():
Ta funkcja jest zbędna - wpisz bezpośrednio:
`config.set_main_option('sqlalchemy.url', f'mysql+pymysql://{DB_ROOT_USER}:{DB_ROOT_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')`

2020-08-31 08:34 UTC, pgs-pdalka commented on app/main.py
> +def api_cv_stats_count() -> Response:
Ten endpoint powinnien przyjmować takie same parametry, jak ten do wyszukiwania użytkowników, czyli listę skilli

2020-08-31 16:08 UTC, aaaandrzej commented on alembic/env.py
> +def get_url():
Robiłem tak wcześniej i miałem z tym rozwiązaniem "dziwny" problem, alembic downgrade base się zawieszał i musiałem odtwarzać bazę łącznie z kasowaniem volume. Jak zmieniłem na to co miałem teraz (z funkcją) to tego problemu nie było. Zmieniłem znowu na to co zasugerowałeś, i problem wrócił. Może to zbieg okoliczności i problem występuje niezależnie, ale mam ponownie takie coś:

(venv) aszulc-mac:CV_Editor andrzejszulc$ export PYTHONPATH=.
(venv) aszulc-mac:CV_Editor andrzejszulc$ DB_HOST=localhost DB_PORT=3306 DB_ROOT_USER=xxx DB_ROOT_PASSWORD=xxx DB_NAME=my_db alembic downgrade base
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade aaaa0b37ea25 -> , start

I tak od kilku minut już to wisi.

2020-08-31 16:09 UTC, aaaandrzej commented on app/main.py
> +def api_cv_stats_count() -> Response:
Wiem, że gadaliśmy o tym, żeby to zostawić, ale zmieniłem to na szybko na POST i przyjmowanie json w postaci najprostszego słownika z jednym skillem i jego levelem.

2020-08-31 16:12 UTC, aaaandrzej commented on app/__temp.py
> +    print(result)
Ogarnąłem użycie czystego SQL za pomocą połączenia do pymysql (skonfigurowane w session.py) ale nie byłem w stanie zmusić tego zapytania do przyjęcia krotki krotek, lub listy krotek, jako parametru.

2020-08-31 16:20 UTC, aaaandrzej commented on alembic/env.py
> +def get_url():
Update - po 10 minutach wreszcie poszło, zrobiłem upgrade head i znowu downgrade base i teraz też wisi na tym samym co powyżej - miałeś tak kiedyś? :) Mam wrażenie, że przy "mojej" implementacji konfiguracji tak nie było

2020-08-31 18:46 UTC, aaaandrzej commented on alembic/env.py
> +def get_url():
Update 2 - wróciłem do wcześniejszego rozwiązania i czasem to idzie od ręki a czasem trwa dłużej, więc chyba problem nie jest związany z tym fragmentem kodu, a te moje dziwne przypadki to był chyba tylko zbieg okoliczności..

2020-09-01 06:20 UTC, pgs-pdalka commented on alembic/env.py
> +def get_url():
Nigdy nie miałem takiego problemu :(

2020-09-01 06:24 UTC, pgs-pdalka commented on app/__temp.py
> +    print(result)
I tak jest wg mnie jak najbardziek OK. Musisz tylko dynamicznie w zapytaniu generować odpowiednią liczbę `%s`. I zmień też `count` na dynamiczny i będzie gotowe :)

P.S. Możesz umieścić wielowierszowy string w potrójnych apostrofach, dzięki czemu nie będziesz musiał niezależnie każedego wiersza owijać. I przypominam o apostrofach, a nie cudzysłowiach ;P

2020-09-01 06:30 UTC, pgs-pdalka commented on app/session.py
> +connection = pymysql.connect(host=DB_HOST,
Już masz nawiązane połączenie, więc nie ma sensu tworzenia kolejnego. Użyj w zapytaniu z czysym SQLem `get_session().execute()`
https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session.execute

2020-09-01 13:54 UTC, aaaandrzej commented on alembic/env.py
> +def get_url():
Ja mam szczęście do dziwnych przypadków, ale jak to nie python, i póki co jest OK, to olejmy to faktycznie.

2020-09-01 13:56 UTC, aaaandrzej commented on app/__temp.py
> +    print(result)
"musisz tylko" z tego komentarza i "odrobinę zmienić format" z poniższego zajęło mnie na sporą część dnia dzisiaj, ale chyba w końcu ogarnąłem - działać działa, zobacz proszę czy z twojej strony to jest akceptowalne :)

2020-09-01 13:59 UTC, aaaandrzej commented on app/session.py
> +connection = pymysql.connect(host=DB_HOST,
Jak wyżej, odrobinę zmienić, czyli również dynamicznie generować kolejne klucze do słownika ze zmiennymi. Pewnie się da to zrobić prościej, ale jakoś sobie z tym (chyba) poradziłem - będę wdzięczny za review całości i jeśli jest OK, to merguję do mastera i robię nowy branch na kolejne rzeczy z TODO.md

2020-09-02 06:33 UTC, pgs-pdalka requested changes

2020-09-02 06:33 UTC, pgs-pdalka commented on app/functions.py
> +        param = {f'param{n}': tuple((skill['skill_name'], skill['skill_level']))}
`tuple` niepotrzebne, bo zdefiniowałeś krotkę, a następnie na jej podstawie stworzyłeś następną
`param = {f'param{n}': (skill['skill_name'], skill['skill_level'])}`

A całą pętelkę można zgrabniej napisać z wykorzystaniem składanych słowników i `enumerate`:
`param = {f'param{n}': (skill['skill_name'], skill['skill_level']) for n, skill in enumerate(json)}`

2020-09-02 06:33 UTC, pgs-pdalka commented on app/functions.py
> +def parse_params(json: dict) -> dict:
`def parse_params(json: List[dict]) -> dict:`

2020-09-02 06:33 UTC, pgs-pdalka commented on app/functions.py
> +def create_param_subs(json: dict) -> str:
`def create_param_subs(json: List[dict]) -> str:`

2020-09-02 06:33 UTC, pgs-pdalka commented on app/functions.py
> +    return param_subs[:-2]
Proponuję jako ciało funkcji coś takiego:
```
return ','.join(f'param{n}' for n in range(len(json)))
```

Zauważ, że po takich zmianach w `parse_params` i w `create_param_subs` numeracja parametrów zaczyna się od 0, czyli `param0`... itd

2020-09-02 06:33 UTC, pgs-pdalka commented on app/functions.py
> +    params.update({'count': len(json)})
Tutaj lepsze będzie bezpośrednie:
`params['count'] = len(json)`

`update` się przydaje, jak chcemy zaktualizować wiele wartości naraz na podstawie podanego słownika

2020-09-02 06:33 UTC, pgs-pdalka commented on app/main.py
> +    sql = ('''
Nawiasy przed i po niepotrzebne

2020-09-02 06:33 UTC, pgs-pdalka commented on app/main.py
> +        users_with_skill_set.append(user)
Proponuję zastąpić pętelkę listą składaną
A `print` dla celów testowych można dać raz dla całej wynikowej listy

2020-09-02 06:33 UTC, pgs-pdalka commented on app/main.py
> +        SELECT COUNT u
Naszym celem jest znalezienie liczby użytkowników, a nie potrzebujemy wiedzieć, jak się nazywają. Dlatego to zapytanie powinno być uproszczone do poniższego (usunięty join do tabeli `user`)
```
SELECT COUNT(r.user_id)
FROM (
    SELECT q.user_id, COUNT(*) as count
    FROM (
        SELECT su.user_id, s.skill_name, su.skill_level
        FROM skill_user su
        JOIN skill s on su.skill_id = s.id
        WHERE (s.skill_name, su.skill_level) IN (%s)''' % create_param_subs(json_data) + '''
    ) q
    GROUP BY q.user_id
) r
WHERE r.count = :count''')
```

2020-09-02 06:33 UTC, pgs-pdalka commented on app/main.py
> +    return make_response({'number_of_users_with_skill_set': len(result)})
Wynikiem zapytania jest jeden wiersz z jedną kolumną, gdzie wpisana jest liczba userów. Więc teraz wystarczy tylko: 
```
result = session.execute(sql, params).scalar()
return make_response({'number_of_users_with_skill_set': result})
```

2020-09-02 08:50 UTC, aaaandrzej commented on app/functions.py
> +    return param_subs[:-2]
`:param` ale fakt, to twoje ładniejsze :)

2020-09-02 08:51 UTC, aaaandrzej commented on app/functions.py
> +        param = {f'param{n}': tuple((skill['skill_name'], skill['skill_level']))}
znałem i lubiłem się z enumerate, ale coś o nim zapomniałem tutaj :D a już nawet zacząłem pisać własny generator, ale porzuciłem ten pomysł szybko ;)

2020-09-02 09:17 UTC, aaaandrzej commented on app/main.py
> +    sql = ('''
Zmienione. Pycharm mi podświetla (**{**subs}) ale wszystko działa - przerzuciłem też zapytania sql do osobnego pliku .py. Tak jest OK, czy to powinno być w plikach .sql? Do functions.py tego nie chciałem wrzucać, bo to stringi, a nie funkcje..

2020-09-02 09:19 UTC, aaaandrzej commented on app/main.py
> +    return make_response({'number_of_users_with_skill_set': len(result)})
Czytałem coś o .scalar() ale nie ćwiczyłem użycia - faktycznie pasuje, dzięki

2020-09-02 09:23 UTC, aaaandrzej commented on app/main.py
> +        users_with_skill_set.append(user)
Print się zaplątał z debugażu, a całość miała być faktycznie zmieniona na list comprehension, ale coś uciekło. Proszę bardzo: `    users_with_skill_set = [{'firstname': user.firstname, 'lastname': user.lastname} for user in result]
`

2020-09-02 09:28 UTC, aaaandrzej commented on app/main.py
> +    sql = ('''
Jeszcze odnośnie zapytań SQL - nie jestem pewny czy dobrze rozumiem twój drugi paragraf o "obu SQLach" - czy ja mam użyć jednego stringa z zapytaniem w obydwu endpointach (teraz używam dwóch)? Da się to zrobić jeszcze jednym formatem, ale mam co do tego wątpliwości, i zostawiłbym tak jak zrobiłem teraz, z 2 osobnymi szablonami. Intuicyjnie to moje wydaje mi się czytelniejsze, ale jeśli to złe podejście, to jestem otwarty na zmiany :)

2020-09-02 09:56 UTC, merged

2020-09-03 07:58 UTC, pgs-pdalka commented on app/main.py
> +    sql = ('''
Jak najbardziej powinno być to w pliku py, bo to ma być bezpośredion dostępne w Pythonie - definiujesz tam zmienne po prostu.

Jak najbadziej powinny być dwa szablony. Komentarz dotyczył obu (czyli każdego z), ale nie miałem na myśli, by robić jeden szablon.